# Generated by Django 6.0.6 on 2026-06-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
        ('computers', '0002_computer_created_at_computer_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='computer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='computers.computer'),
            preserve_default=False,
        ),
    ]
